name: github_bloc_one
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  flutter_bloc:
  equatable:

  dio:

  sizer:

  flutter_svg:
  google_fonts:

  auto_route:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
